### ISSUE TITLE
Chrome Android Issue (and solution )

### ISSUE THREAD

**Issue by MrVinz** [leemachin/say-cheese#26]
Hello and thank you for Say-cheese,

I had an issue on android with both my SIII and nexus 9, the video stream wasn't playing and i got a single "freeze" with the first captured image. I've simply added `this.video.autoplay=true;` on line 92 and it solved the problem.

KR,

Vincent

**Comment by marcioamr** [comment]
The problem persists and the solution worked for me. Tks.

**Comment by Javier-Rotelli** [comment]
@MrVinz i can submit a pull request. the only change is that one you mention?
have you tested it on other devices?

**Comment by MrVinz** [comment]
@Javier-Rotelli i tested it on android tab and smartphone, laptop under linux (chrome and FF) and on windows (chrome) and was working. if @leemachin is still active on say-cheese the modification takes 10 sec, otherwise a fork could be possible ? on a personal project i also  did something like in the pull request #27

**Comment by Javier-Rotelli** [comment]
uhm, ok, i'll do the pull request then. i'll fork, but i'm not sure if i could maintain this.

**Comment by fsteinbauer** [comment]
+1
